# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fledge - CI/CD for Flutter
email: mmccabe@orbsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  Fledge - CI/CD for flutter. Automatically build, test (including integration tests),
  sign and release your Flutter app to both Apple and Google stores. Supports
  tracing-back from any version of app to your source code.
baseurl: "/fledge" # the subpath of your site, e.g. /blog
url: "https://mmcc007.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nocnoc
github_username:  mmcc007

# Build settings
markdown: kramdown
#theme: minima
theme: just-the-docs
#plugins:
#  - jekyll-feed

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/mmcc007/fledge"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
