name: fledge
description: A CICD solution for Flutter. Automates build, testing and signing on a number of supported build servers. Also automates upload to Google and Apple stores for release to beta testers and full release.
version: 0.0.1
homepage: https://www.github.com/mmcc007/fledge
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  resource: ^2.1.5
#  package_info: ^0.4.0

dev_dependencies:
  test: ^1.0.0

executables:
  fledge: main
